Efrs-727: caching models
exadel-inc/CompreFace pull request #135
Opened 2020-09-24 08:43 UTC by daffy-

2020-09-26 20:45 UTC, mmisachenka commented on api/src/main/java/com/exadel/frs/core/trainservice/handler/ExceptionCode.java
> -    MODEL_HAS_NOT_ENOUGH_FACES(30, BAD_REQUEST),
MODEL_NOT_TRAINED/MODEL_ALREADY_LOCKED codes with related exceptions are not used any more

2020-09-28 07:06 UTC, mmisachenka requested changes

2020-09-28 07:06 UTC, mmisachenka commented on api/src/main/java/com/exadel/frs/core/trainservice/cache/FaceBO.java
> -import lombok.AllArgsConstructor;
123

2020-09-28 07:46 UTC, daffy- commented on api/src/main/java/com/exadel/frs/core/trainservice/cache/FaceBO.java
> -import lombok.AllArgsConstructor;
fixed

2020-09-28 10:03 UTC, merged