EFRS-846 - created an endpoint for cloning collections and added test…
exadel-inc/CompreFace pull request #216
Opened 2020-11-13 09:43 UTC by AleksKurilo

…s for this case

2020-11-13 09:44 UTC, AleksKurilo commented
I have read the CLA Document and I hereby sign the CLA

2020-11-13 11:59 UTC, andreigaevsky requested changes

2020-11-13 11:59 UTC, andreigaevsky commented on admin/src/main/java/com/exadel/frs/service/ModelService.java
> +    public Model cloneModel(
What about faces? We also should copy them into new model. Please, check `MigrateController.java`  and `MigrationComponent.java`

2020-11-13 11:59 UTC, andreigaevsky commented on admin/src/main/java/com/exadel/frs/controller/ModelController.java
> +            @PathVariable final String orgGuid,
Please, use `team_codestyle.xml` from the `dev` folder.

2020-11-17 16:06 UTC, andreigaevsky requested changes

2020-11-17 16:06 UTC, andreigaevsky commented on admin/src/main/java/com/exadel/frs/service/ModelService.java
> +        val feces = facesRepository.findByApiKey(model.getApiKey());
Just typo. Please, rename to `faces`

2020-11-17 16:06 UTC, andreigaevsky commented on admin/src/main/java/com/exadel/frs/service/ModelService.java
> +            Face cloneFace = new Face(face);
Please, replace with `val` everywhere

2020-11-17 16:06 UTC, andreigaevsky commented on admin/src/main/java/com/exadel/frs/service/ModelService.java
> +        clone.setAppModelAccess(new ArrayList<>());
Maybe it's better to leave access type to a clone

2020-12-01 10:57 UTC, pospielov approved these changes

2020-12-01 11:16 UTC, andreigaevsky approved these changes

2020-12-01 11:17 UTC, merged