Adjust validation for subject name - do not allow null value and empty value
exadel-inc/CompreFace pull request #618
Opened 2021-10-02 12:50 UTC by mslowiak

Adjusted validation in three places:
- `EmbeddingController`
- `SubjectController`
- `SubjectDto`

Replaced NotNull with NotBlank annotation (which checks it the value is the null or empty)

Performed some manual tests to check behaviour after fix

2021-10-02 12:51 UTC, mslowiak commented
I have read the CLA Document and I hereby sign the CLA

2021-10-02 12:51 UTC, mslowiak commented
recheckcla

2021-10-03 14:57 UTC, mslowiak commented
@pospielov 
Would you mind taking a look at this? :)

2021-10-04 10:06 UTC, pospielov requested changes
The validation doesn't work
Please check this:
https://stackoverflow.com/a/62386664
I believe it should start working after you add this annotation.

https://documenter.getpostman.com/view/17578263/UUxzAnde#66d07d92-f7b7-4e4c-a993-5ae3f487ed8e
here is the postman collection to check if it works

2021-10-04 10:06 UTC, pospielov commented on java/api/src/main/java/com/exadel/frs/core/trainservice/controller/EmbeddingController.java
> +            @ApiParam(value = SUBJECT_DESC, required = true) @Valid @NotBlank(message = "Subject name is empty") @RequestParam(SUBJECT) final String subjectName,
Please move the message here:
com.exadel.frs.core.trainservice.system.global.Constants

2021-10-04 16:16 UTC, mslowiak commented
@pospielov I fixed the review comments

2021-10-05 07:31 UTC, pospielov approved these changes

2021-10-05 07:31 UTC, merged

2021-10-05 07:32 UTC, pospielov commented
Thanks for your contribution! :)